In [16]:
from sklearn.cluster import SpectralBiclustering
import pandas as pd
import numpy as np
import scipy.linalg as sp 
import random

In [19]:
#creat friendship diagonal matrix 1000*1000
m=1000
friendship = np.zeros((m, m))
for i in range(0,m):
    for j in range(0,m):
        if i == j:
            friendship[i,i]=1
        elif j>i:
            friendship[i,j]=random.randint(0, 1)
for i in range(0,m):
    for j in range(0,m):
        if i>j:
            friendship[i,j]=friendship[j,i]
friendship

array([[1., 0., 0., ..., 0., 1., 1.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 1., 0., 1.],
       ...,
       [0., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.]])

In [6]:
rating = pd.read_csv('ratings.csv')

In [7]:
# Deleting columns
data = rating.drop(["timestamp"], axis=1)

In [8]:
data.head()

userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [9]:
cluster = SpectralBiclustering(n_clusters=2,random_state=0).fit(data)

In [10]:
cluster.row_labels_

array([0, 0, 0, ..., 1, 1, 1])

In [11]:
cluster.column_labels_

array([0, 1, 0])

In [9]:
cluster.biclusters_

(array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]]),
 array([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True],
        [False,  True, False]]))

In [12]:
cluster.rows_

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True]])

In [13]:
cluster.columns_

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False]])